### ISSUE TITLE
Use AltF12 to automatically build, run example tests and submit if tests pass.

### ISSUE THREAD

**Issue by nadimakhtar97** [pustaczek/icie#21]

**Comment by nadimakhtar97** [comment]
I am getting this problem while submitting on SPOJ too. 
Please solve this issue.

**Comment by pustaczek** [comment]
I managed to come up with an idea of what may be going wrong and reproduced the problem: are you trying to submit a Division 1 problem from a Division 2 account?

The bug works like this: on CodeChef some contests have two versions for each division, so my extension automatically detects your division and redirects you to the appropriate version. However, CodeChef includes tasks from the other division on the "non scorable" list, under the normal problem list. They need to be submitted to e.g. /submit/INVXOR URL instead of a /MARCH20B/submit/INVXOR URL. Hence, the extension sends a request to the wrong URL, gets an unexpected response and shows the original error.

I will try to fix the problem soon, detecting this case should not be too bad.

**Comment by nadimakhtar97** [comment]
Thanks for responding to this issue.
As you said this issue arises when the division 1 problem is submitted from a division 2 account. But this was not the case in my situation, I did try to submit a division 1 problem from a division 1 account.
Moreover, I agree with you that somewhere that the extension is sending a request to a wrong URL.

**Comment by pustaczek** [comment]
I have noticed that the problem also happens when submitting to contests that ended. Was that the case? I pushed 0.7.7 with an attempted fix for both situations, so feel free to check and tell whether it worked.

**Comment by nadimakhtar97** [comment]
I tried your update(0.7.7) on  April Challenge 2020 Division 2 on question COVID Pandemic and Long Queue. But it seems like it is still unable to parse the language from list of available language.
![Screenshot from 2020-04-03 19-19-48](https://user-images.githubusercontent.com/48604201/78367797-4640d700-75e0-11ea-8e26-c9be2059af71.png)

**Comment by pustaczek** [comment]
Submitting this problem from my account works, and the only difference I know of are our divisions. You said you're div1, and you're trying to submit to the div2 contest. Does the problem still exist if you submit to the [same task on div1 contest](https://www.codechef.com/APRIL20A/problems/COVIDLQ)? If you try manually submitting through [this link](https://www.codechef.com/APRIL20B/submit/COVIDLQ), do you get a "You do not belong to this division" error?

**Comment by nadimakhtar97** [comment]
Each time I submit a solution a warning appears on CodeChef (You have been logged out since we have a session limit of 1 per user).
![Screenshot from 2020-04-08 20-47-05](https://user-images.githubusercontent.com/48604201/78801589-8639fc80-79da-11ea-9d69-5b6772fc24bb.png)
![Screenshot from 2020-04-08 20-50-13](https://user-images.githubusercontent.com/48604201/78801662-96ea7280-79da-11ea-966e-9b43d680811e.png)

**Comment by pustaczek** [comment]
Yeah, that's unfortunately just how CodeChef works. It doesn't allow logins from two browsers at once (e.g. chrome and firefox, or chrome and icie). This isn't the cause of the error though, the extension detects this and logs in again correctly.

As for fixing this, in the next few days I will add more logging and some kind of manual extended error reports. This should hopefully let me see what's going wrong, I'll write here when it's ready.

**Comment by Imperial-lord** [comment]
I'm facing the same issue with CodeChef March CookOff (as a practice contest). The test cases are not being shown and neither I'm I able to submit. I hope it gets fixed soon!

**Comment by pustaczek** [comment]
I've released 0.7.13 with the manual error reports I mentioned. Could you try to reproduce the error again and collect the details (just press "Report this" and the extension will display more info)?

**Comment by krsinghshubham** [comment]
I also got this same problem while trying to submit a problem .
This problem was not part of any present contests.
error: website could not be analyzed; not found '#edit-language'; 
[report issue?](https://github.com/pustaczek/icie/issues)
